# Powerlevel10k prompt config inspired by dotfiles/zsh/.p10k.zsh from the
# reference repo, but trimmed down to the segments that matter for this setup.

typeset -g POWERLEVEL9K_MODE=nerdfont-v3
typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
typeset -g POWERLEVEL9K_ICON_PADDING=none

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  os_icon
  dir
  vcs
  newline
  prompt_char
)

typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status
  command_execution_time
  background_jobs
  kubecontext
  terraform
  aws
  newline
)

typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%244F╭─'
typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='%244F├─'
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%244F╰─'
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_CHAR='─'
typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_GAP_FOREGROUND=244

typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B1'
typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B3'
typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B0'
typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B2'
typeset -g POWERLEVEL9K_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL='\uE0B0'
typeset -g POWERLEVEL9K_RIGHT_PROMPT_FIRST_SEGMENT_START_SYMBOL='\uE0B2'
typeset -g POWERLEVEL9K_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=''
typeset -g POWERLEVEL9K_RIGHT_PROMPT_LAST_SEGMENT_END_SYMBOL=''

typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=232
typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=7

typeset -g POWERLEVEL9K_DIR_BACKGROUND=4
typeset -g POWERLEVEL9K_DIR_FOREGROUND=254
typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=250
typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=255
typeset -g POWERLEVEL9K_DIR_ANCHOR_BOLD=true
typeset -g POWERLEVEL9K_SHORTEN_STRATEGY=truncate_to_unique
typeset -g POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=80
typeset -g POWERLEVEL9K_DIR_MIN_COMMAND_COLUMNS=40

typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=2
typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=3
typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=2
typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=3
typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=8
typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='~'
typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1

typeset -g POWERLEVEL9K_PROMPT_CHAR_BACKGROUND=
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND=76
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND=196
typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION='❯'
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_LAST_SEGMENT_END_SYMBOL=
typeset -g POWERLEVEL9K_PROMPT_CHAR_LEFT_PROMPT_FIRST_SEGMENT_START_SYMBOL=

typeset -g POWERLEVEL9K_STATUS_OK=true
typeset -g POWERLEVEL9K_STATUS_OK_VISUAL_IDENTIFIER_EXPANSION='✔'
typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=2
typeset -g POWERLEVEL9K_STATUS_ERROR_VISUAL_IDENTIFIER_EXPANSION='✘'
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=1

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=0
typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=3

typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false

typeset -g POWERLEVEL9K_KUBECONTEXT_BACKGROUND=6
typeset -g POWERLEVEL9K_KUBECONTEXT_FOREGROUND=0
typeset -g POWERLEVEL9K_TERRAFORM_BACKGROUND=5
typeset -g POWERLEVEL9K_TERRAFORM_FOREGROUND=0
typeset -g POWERLEVEL9K_AWS_BACKGROUND=1
typeset -g POWERLEVEL9K_AWS_FOREGROUND=255

# Show cloud/devops context only when it is likely to matter.
typeset -g POWERLEVEL9K_KUBECONTEXT_SHOW_ON_COMMAND='kubectl|k|helm|kubens|kns|kubectx|kctx|oc|k9s|helmfile|flux|stern'
typeset -g POWERLEVEL9K_TERRAFORM_SHOW_ON_COMMAND='terraform|tf|terragrunt|tg|tofu'
typeset -g POWERLEVEL9K_AWS_SHOW_ON_COMMAND='aws|terraform|tf|terragrunt|tg|pulumi'

# Kubernetes: highlight production contexts and include namespace when it isn't default.
typeset -g POWERLEVEL9K_KUBECONTEXT_CLASSES=(
  '*prod*|*production*' PROD
  '*stag*|*stage*|*uat*' STAGE
  '*dev*|*sandbox*' DEV
  '*'                    DEFAULT
)
typeset -g POWERLEVEL9K_KUBECONTEXT_PROD_FOREGROUND=15
typeset -g POWERLEVEL9K_KUBECONTEXT_PROD_BACKGROUND=1
typeset -g POWERLEVEL9K_KUBECONTEXT_STAGE_FOREGROUND=0
typeset -g POWERLEVEL9K_KUBECONTEXT_STAGE_BACKGROUND=3
typeset -g POWERLEVEL9K_KUBECONTEXT_DEV_FOREGROUND=0
typeset -g POWERLEVEL9K_KUBECONTEXT_DEV_BACKGROUND=2
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_FOREGROUND=7
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_BACKGROUND=5
typeset -g POWERLEVEL9K_KUBECONTEXT_PREFIX='k8s '
typeset -g POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION=
POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='${P9K_KUBECONTEXT_CLOUD_CLUSTER:-${P9K_KUBECONTEXT_NAME}}'
POWERLEVEL9K_KUBECONTEXT_DEFAULT_CONTENT_EXPANSION+='${${:-/$P9K_KUBECONTEXT_NAMESPACE}:#/default}'

# Terraform: make workspace obvious and highlight risky environments.
typeset -g POWERLEVEL9K_TERRAFORM_SHOW_DEFAULT=false
typeset -g POWERLEVEL9K_TERRAFORM_CLASSES=(
  '*prod*|*production*' PROD
  '*stag*|*stage*|*uat*' STAGE
  '*dev*|*sandbox*' DEV
  '*'                    OTHER
)
typeset -g POWERLEVEL9K_TERRAFORM_PREFIX='tf '
typeset -g POWERLEVEL9K_TERRAFORM_PROD_FOREGROUND=15
typeset -g POWERLEVEL9K_TERRAFORM_PROD_BACKGROUND=1
typeset -g POWERLEVEL9K_TERRAFORM_STAGE_FOREGROUND=0
typeset -g POWERLEVEL9K_TERRAFORM_STAGE_BACKGROUND=3
typeset -g POWERLEVEL9K_TERRAFORM_DEV_FOREGROUND=0
typeset -g POWERLEVEL9K_TERRAFORM_DEV_BACKGROUND=2
typeset -g POWERLEVEL9K_TERRAFORM_OTHER_FOREGROUND=4
typeset -g POWERLEVEL9K_TERRAFORM_OTHER_BACKGROUND=0
typeset -g POWERLEVEL9K_TERRAFORM_CONTENT_EXPANSION='${P9K_CONTENT//\%/%%}'

# AWS: keep the segment quiet until an AWS-aware command is in flight.
typeset -g POWERLEVEL9K_AWS_CLASSES=(
  '*prod*|*production*' PROD
  '*stag*|*stage*|*uat*' STAGE
  '*dev*|*sandbox*' DEV
  '*'                    DEFAULT
)
typeset -g POWERLEVEL9K_AWS_PREFIX='aws '
typeset -g POWERLEVEL9K_AWS_PROD_FOREGROUND=15
typeset -g POWERLEVEL9K_AWS_PROD_BACKGROUND=1
typeset -g POWERLEVEL9K_AWS_STAGE_FOREGROUND=0
typeset -g POWERLEVEL9K_AWS_STAGE_BACKGROUND=3
typeset -g POWERLEVEL9K_AWS_DEV_FOREGROUND=0
typeset -g POWERLEVEL9K_AWS_DEV_BACKGROUND=2
typeset -g POWERLEVEL9K_AWS_DEFAULT_FOREGROUND=7
typeset -g POWERLEVEL9K_AWS_DEFAULT_BACKGROUND=1
typeset -g POWERLEVEL9K_AWS_CONTENT_EXPANSION='${P9K_AWS_PROFILE//\%/%%}${P9K_AWS_REGION:+ ${P9K_AWS_REGION//\%/%%}}'
